spring:
  application:
    name: face-recognition
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://b.sww.moe:33307/face?characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    database: mysql

baidu:
  clientId: 'your_client_id'
  clientSecret: 'your_client_secret'
