spring:
  application:
    name: face-recognition
  profiles:
    active: dev
#    active: devuto
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    open-in-view: true

baidu:
  clientId: '26003518'
  clientSecret: '9rwrbO5iLq99hZDTnxb6Y96p'
  secretKey: 'TfS9Vptvpy0YLyiTy47btH06Kh7YBlD5'
